//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.11001.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.flickr.com/services/rest/?method=flickr.{operation}&api_key={apiKey}&f" +
            "ormat=json&nojsoncallback=1")]
        public string FlickrUri {
            get {
                return ((string)(this["FlickrUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("be9b6f66bd7a1c0c0f1465a1b7e8a764")]
        public string FlickrApiKey {
            get {
                return ((string)(this["FlickrApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservices.amazon.com/onca/xml?Service=AWSECommerceService&SubscriptionId" +
            "={subscriptionID}&Operation={operation}")]
        public string AmazonUri {
            get {
                return ((string)(this["AmazonUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1S494ZXP934WJ38NH5R2")]
        public string AmazonSubscriptionID {
            get {
                return ((string)(this["AmazonSubscriptionID"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.{operation}.live.net/json.aspx?AppId={appID}&Market=en-US&Sources=web")]
        public string LiveSearchUri {
            get {
                return ((string)(this["LiveSearchUri"]));
            }
            set {
                this["LiveSearchUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40EA1F3C4F04BE0EA8F0461962A8F8EAC4D773D3")]
        public string LiveSearchApiKey {
            get {
                return ((string)(this["LiveSearchApiKey"]));
            }
            set {
                this["LiveSearchApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajax.googleapis.com/ajax/services/{operation}/web?v=1.0")]
        public string GoogleSearchUri {
            get {
                return ((string)(this["GoogleSearchUri"]));
            }
            set {
                this["GoogleSearchUri"] = value;
            }
        }
    }
}
